version: "3"

services:
  server:
    build: server
    container_name: server
    command: sh ./docker-entrypoint.sh
    restart: always
    ports:
      - 8001:8001

  client:
    build: client
    container_name: client
    command: sh ./docker-entrypoint.sh
    restart: always
    ports:
      - 8002:8002
