version: "3"

services:
  server:
    build: server
    container_name: server
    command: sh ./docker-entrypoint.sh
    restart: always
    ports:
      - 4001:4001
    volumes:
      - ./protos/:/usr/app/protos

  client:
    build: client
    container_name: client
    command: sh ./docker-entrypoint.sh
    restart: always
    ports:
      - 4002:4002
    volumes:
      - ./protos/:/usr/app/protos
    depends_on:
      - server
